var searchData=
[
  ['objectname',['objectName',['http://doc.qt.io/qt-5/qobject.html#objectName-prop',0,'QObject']]],
  ['offlinestoragepath',['offlineStoragePath',['http://doc.qt.io/qt-5/qqmlengine.html#offlineStoragePath-prop',0,'QQmlEngine']]],
  ['offset',['offset',['http://doc.qt.io/qt-5/qgraphicsdropshadoweffect.html#offset-prop',0,'QGraphicsDropShadowEffect::offset()'],['http://doc.qt.io/qt-5/qpangesture.html#offset-prop',0,'QPanGesture::offset()']]],
  ['offtherecord',['offTheRecord',['http://doc.qt.io/qt-5/qquickwebengineprofile.html#offTheRecord-prop',0,'QQuickWebEngineProfile']]],
  ['okbuttontext',['okButtonText',['http://doc.qt.io/qt-5/qinputdialog.html#okButtonText-prop',0,'QInputDialog']]],
  ['opacity',['opacity',['http://doc.qt.io/qt-5/qquickitem.html#opacity-prop',0,'QQuickItem::opacity()'],['http://doc.qt.io/qt-5/qwindow.html#opacity-prop',0,'QWindow::opacity()'],['http://doc.qt.io/qt-5/qgraphicsopacityeffect.html#opacity-prop',0,'QGraphicsOpacityEffect::opacity()'],['http://doc.qt.io/qt-5/qgraphicsobject.html#opacity-prop',0,'QGraphicsObject::opacity()']]],
  ['opacitymask',['opacityMask',['http://doc.qt.io/qt-5/qgraphicsopacityeffect.html#opacityMask-prop',0,'QGraphicsOpacityEffect']]],
  ['opaqueresize',['opaqueResize',['http://doc.qt.io/qt-5/qsplitter.html#opaqueResize-prop',0,'QSplitter']]],
  ['openexternallinks',['openExternalLinks',['http://doc.qt.io/qt-5/qgraphicstextitem.html#openExternalLinks-prop',0,'QGraphicsTextItem::openExternalLinks()'],['http://doc.qt.io/qt-5/qlabel.html#openExternalLinks-prop',0,'QLabel::openExternalLinks()'],['http://doc.qt.io/qt-5/qtextbrowser.html#openExternalLinks-prop',0,'QTextBrowser::openExternalLinks()']]],
  ['openlinks',['openLinks',['http://doc.qt.io/qt-5/qtextbrowser.html#openLinks-prop',0,'QTextBrowser']]],
  ['optimizationflags',['optimizationFlags',['http://doc.qt.io/qt-5/qgraphicsview.html#optimizationFlags-prop',0,'QGraphicsView']]],
  ['options',['options',['http://doc.qt.io/qt-5/qprintdialog.html#options-prop',0,'QPrintDialog::options()'],['http://doc.qt.io/qt-5/qcolordialog.html#options-prop',0,'QColorDialog::options()'],['http://doc.qt.io/qt-5/qfiledialog.html#options-prop',0,'QFileDialog::options()'],['http://doc.qt.io/qt-5/qfontdialog.html#options-prop',0,'QFontDialog::options()'],['http://doc.qt.io/qt-5/qinputdialog.html#options-prop',0,'QInputDialog::options()'],['http://doc.qt.io/qt-5/qwizard.html#options-prop',0,'QWizard::options()']]],
  ['organizationdomain',['organizationDomain',['http://doc.qt.io/qt-5/qcoreapplication.html#organizationDomain-prop',0,'QCoreApplication']]],
  ['organizationname',['organizationName',['http://doc.qt.io/qt-5/qcoreapplication.html#organizationName-prop',0,'QCoreApplication']]],
  ['orientation',['orientation',['http://doc.qt.io/qt-5/qorientationreading.html#orientation-prop',0,'QOrientationReading::orientation()'],['http://doc.qt.io/qt-5/qscreen.html#orientation-prop',0,'QScreen::orientation()'],['http://doc.qt.io/qt-5/qdatawidgetmapper.html#orientation-prop',0,'QDataWidgetMapper::orientation()'],['http://doc.qt.io/qt-5/qabstractslider.html#orientation-prop',0,'QAbstractSlider::orientation()'],['http://doc.qt.io/qt-5/qdialogbuttonbox.html#orientation-prop',0,'QDialogButtonBox::orientation()'],['http://doc.qt.io/qt-5/qprogressbar.html#orientation-prop',0,'QProgressBar::orientation()'],['http://doc.qt.io/qt-5/qsplitter.html#orientation-prop',0,'QSplitter::orientation()'],['http://doc.qt.io/qt-5/qtoolbar.html#orientation-prop',0,'QToolBar::orientation()']]],
  ['origin',['origin',['http://doc.qt.io/qt-5/qwebenginefullscreenrequest.html#origin-prop',0,'QWebEngineFullScreenRequest::origin()'],['http://doc.qt.io/qt-5/qgraphicsscale.html#origin-prop',0,'QGraphicsScale::origin()'],['http://doc.qt.io/qt-5/qgraphicsrotation.html#origin-prop',0,'QGraphicsRotation::origin()']]],
  ['outputdevice',['outputDevice',['http://doc.qt.io/qt-5/qsvggenerator.html#outputDevice-prop',0,'QSvgGenerator']]],
  ['outputrange',['outputRange',['http://doc.qt.io/qt-5/qsensor.html#outputRange-prop',0,'QSensor']]],
  ['outputranges',['outputRanges',['http://doc.qt.io/qt-5/qsensor.html#outputRanges-prop',0,'QSensor']]],
  ['overwritemode',['overwriteMode',['http://doc.qt.io/qt-5/qplaintextedit.html#overwriteMode-prop',0,'QPlainTextEdit::overwriteMode()'],['http://doc.qt.io/qt-5/qtextedit.html#overwriteMode-prop',0,'QTextEdit::overwriteMode()']]]
];
