var searchData=
[
  ['wascanceled',['wasCanceled',['http://doc.qt.io/qt-5/qprogressdialog.html#wasCanceled-prop',0,'QProgressDialog']]],
  ['whatsthis',['whatsThis',['http://doc.qt.io/qt-5/qaction.html#whatsThis-prop',0,'QAction::whatsThis()'],['http://doc.qt.io/qt-5/qshortcut.html#whatsThis-prop',0,'QShortcut::whatsThis()'],['http://doc.qt.io/qt-5/qwidget.html#whatsThis-prop',0,'QWidget::whatsThis()']]],
  ['wheelscrolllines',['wheelScrollLines',['http://doc.qt.io/qt-5/qapplication.html#wheelScrollLines-prop',0,'QApplication']]],
  ['widgetresizable',['widgetResizable',['http://doc.qt.io/qt-5/qscrollarea.html#widgetResizable-prop',0,'QScrollArea']]],
  ['width',['width',['http://doc.qt.io/qt-5/qgeorectangle.html#width-prop',0,'QGeoRectangle::width()'],['http://doc.qt.io/qt-5/qquickitem.html#width-prop',0,'QQuickItem::width()'],['http://doc.qt.io/qt-5/qwindow.html#width-prop',0,'QWindow::width()'],['http://doc.qt.io/qt-5/qwidget.html#width-prop',0,'QWidget::width()']]],
  ['windowfilepath',['windowFilePath',['http://doc.qt.io/qt-5/qwidget.html#windowFilePath-prop',0,'QWidget']]],
  ['windowflags',['windowFlags',['http://doc.qt.io/qt-5/qgraphicswidget.html#windowFlags-prop',0,'QGraphicsWidget::windowFlags()'],['http://doc.qt.io/qt-5/qwidget.html#windowFlags-prop',0,'QWidget::windowFlags()']]],
  ['windowicon',['windowIcon',['http://doc.qt.io/qt-5/qguiapplication.html#windowIcon-prop',0,'QGuiApplication::windowIcon()'],['http://doc.qt.io/qt-5/qapplication.html#windowIcon-prop',0,'QApplication::windowIcon()'],['http://doc.qt.io/qt-5/qwidget.html#windowIcon-prop',0,'QWidget::windowIcon()']]],
  ['windowicontext',['windowIconText',['http://doc.qt.io/qt-5/qwidget-obsolete.html#windowIconText-prop',0,'QWidget']]],
  ['windowmodality',['windowModality',['http://doc.qt.io/qt-5/qwidget.html#windowModality-prop',0,'QWidget']]],
  ['windowmodified',['windowModified',['http://doc.qt.io/qt-5/qwidget.html#windowModified-prop',0,'QWidget']]],
  ['windowopacity',['windowOpacity',['http://doc.qt.io/qt-5/qwidget.html#windowOpacity-prop',0,'QWidget']]],
  ['windowtitle',['windowTitle',['http://doc.qt.io/qt-5/qgraphicswidget.html#windowTitle-prop',0,'QGraphicsWidget::windowTitle()'],['http://doc.qt.io/qt-5/qwidget.html#windowTitle-prop',0,'QWidget::windowTitle()'],['http://doc.qt.io/qt-5/qdockwidget.html#windowTitle-prop',0,'QDockWidget::windowTitle()']]],
  ['wizardstyle',['wizardStyle',['http://doc.qt.io/qt-5/qwizard.html#wizardStyle-prop',0,'QWizard']]],
  ['wordwrap',['wordWrap',['http://doc.qt.io/qt-5/qlistview.html#wordWrap-prop',0,'QListView::wordWrap()'],['http://doc.qt.io/qt-5/qtableview.html#wordWrap-prop',0,'QTableView::wordWrap()'],['http://doc.qt.io/qt-5/qtreeview.html#wordWrap-prop',0,'QTreeView::wordWrap()'],['http://doc.qt.io/qt-5/qlabel.html#wordWrap-prop',0,'QLabel::wordWrap()']]],
  ['wordwrapmode',['wordWrapMode',['http://doc.qt.io/qt-5/qplaintextedit.html#wordWrapMode-prop',0,'QPlainTextEdit::wordWrapMode()'],['http://doc.qt.io/qt-5/qtextedit.html#wordWrapMode-prop',0,'QTextEdit::wordWrapMode()']]],
  ['wraparound',['wrapAround',['http://doc.qt.io/qt-5/qcompleter.html#wrapAround-prop',0,'QCompleter']]],
  ['wrapping',['wrapping',['http://doc.qt.io/qt-5/qabstractspinbox.html#wrapping-prop',0,'QAbstractSpinBox::wrapping()'],['http://doc.qt.io/qt-5/qdial.html#wrapping-prop',0,'QDial::wrapping()']]],
  ['writingsystem',['writingSystem',['http://doc.qt.io/qt-5/qfontcombobox.html#writingSystem-prop',0,'QFontComboBox']]]
];
