var searchData=
[
  ['objectname',['objectName',['https://doc.qt.io/qt-5/qobject.html#objectName-prop',0,'QObject']]],
  ['offlinestoragepath',['offlineStoragePath',['https://doc.qt.io/qt-5/qqmlengine.html#offlineStoragePath-prop',0,'QQmlEngine']]],
  ['offset',['offset',['https://doc.qt.io/qt-5/qgraphicsdropshadoweffect.html#offset-prop',0,'QGraphicsDropShadowEffect::offset()'],['https://doc.qt.io/qt-5/qpangesture.html#offset-prop',0,'QPanGesture::offset()']]],
  ['offtherecord',['offTheRecord',['https://doc.qt.io/qt-5/qquickwebengineprofile.html#offTheRecord-prop',0,'QQuickWebEngineProfile']]],
  ['okbuttontext',['okButtonText',['https://doc.qt.io/qt-5/qinputdialog.html#okButtonText-prop',0,'QInputDialog']]],
  ['opacity',['opacity',['https://doc.qt.io/qt-5/qgraphicsopacityeffect.html#opacity-prop',0,'QGraphicsOpacityEffect::opacity()'],['https://doc.qt.io/qt-5/qgraphicsobject.html#opacity-prop',0,'QGraphicsObject::opacity()'],['https://doc.qt.io/qt-5/qwindow.html#opacity-prop',0,'QWindow::opacity()'],['https://doc.qt.io/qt-5/qquickitem.html#opacity-prop',0,'QQuickItem::opacity()']]],
  ['opacitymask',['opacityMask',['https://doc.qt.io/qt-5/qgraphicsopacityeffect.html#opacityMask-prop',0,'QGraphicsOpacityEffect']]],
  ['opaqueresize',['opaqueResize',['https://doc.qt.io/qt-5/qsplitter.html#opaqueResize-prop',0,'QSplitter']]],
  ['openexternallinks',['openExternalLinks',['https://doc.qt.io/qt-5/qgraphicstextitem.html#openExternalLinks-prop',0,'QGraphicsTextItem::openExternalLinks()'],['https://doc.qt.io/qt-5/qlabel.html#openExternalLinks-prop',0,'QLabel::openExternalLinks()'],['https://doc.qt.io/qt-5/qtextbrowser.html#openExternalLinks-prop',0,'QTextBrowser::openExternalLinks()']]],
  ['openlinks',['openLinks',['https://doc.qt.io/qt-5/qtextbrowser.html#openLinks-prop',0,'QTextBrowser']]],
  ['optimizationflags',['optimizationFlags',['https://doc.qt.io/qt-5/qgraphicsview.html#optimizationFlags-prop',0,'QGraphicsView']]],
  ['options',['options',['https://doc.qt.io/qt-5/qprintdialog.html#options-prop',0,'QPrintDialog::options()'],['https://doc.qt.io/qt-5/qcolordialog.html#options-prop',0,'QColorDialog::options()'],['https://doc.qt.io/qt-5/qfiledialog.html#options-prop',0,'QFileDialog::options()'],['https://doc.qt.io/qt-5/qfontdialog.html#options-prop',0,'QFontDialog::options()'],['https://doc.qt.io/qt-5/qinputdialog.html#options-prop',0,'QInputDialog::options()'],['https://doc.qt.io/qt-5/qwizard.html#options-prop',0,'QWizard::options()']]],
  ['organizationdomain',['organizationDomain',['https://doc.qt.io/qt-5/qcoreapplication.html#organizationDomain-prop',0,'QCoreApplication']]],
  ['organizationname',['organizationName',['https://doc.qt.io/qt-5/qcoreapplication.html#organizationName-prop',0,'QCoreApplication']]],
  ['orientation',['orientation',['https://doc.qt.io/qt-5/qdatawidgetmapper.html#orientation-prop',0,'QDataWidgetMapper::orientation()'],['https://doc.qt.io/qt-5/qabstractslider.html#orientation-prop',0,'QAbstractSlider::orientation()'],['https://doc.qt.io/qt-5/qdialogbuttonbox.html#orientation-prop',0,'QDialogButtonBox::orientation()'],['https://doc.qt.io/qt-5/qprogressbar.html#orientation-prop',0,'QProgressBar::orientation()'],['https://doc.qt.io/qt-5/qsplitter.html#orientation-prop',0,'QSplitter::orientation()'],['https://doc.qt.io/qt-5/qtoolbar.html#orientation-prop',0,'QToolBar::orientation()'],['https://doc.qt.io/qt-5/qscreen.html#orientation-prop',0,'QScreen::orientation()'],['https://doc.qt.io/qt-5/qorientationreading.html#orientation-prop',0,'QOrientationReading::orientation()']]],
  ['origin',['origin',['https://doc.qt.io/qt-5/qgraphicsscale.html#origin-prop',0,'QGraphicsScale::origin()'],['https://doc.qt.io/qt-5/qgraphicsrotation.html#origin-prop',0,'QGraphicsRotation::origin()'],['https://doc.qt.io/qt-5/qwebenginefullscreenrequest.html#origin-prop',0,'QWebEngineFullScreenRequest::origin()'],['https://doc.qt.io/qt-5/qscxmlevent.html#origin-prop',0,'QScxmlEvent::origin()']]],
  ['origintype',['originType',['https://doc.qt.io/qt-5/qscxmlevent.html#originType-prop',0,'QScxmlEvent']]],
  ['outputdevice',['outputDevice',['https://doc.qt.io/qt-5/qsvggenerator.html#outputDevice-prop',0,'QSvgGenerator']]],
  ['outputrange',['outputRange',['https://doc.qt.io/qt-5/qsensor.html#outputRange-prop',0,'QSensor']]],
  ['outputranges',['outputRanges',['https://doc.qt.io/qt-5/qsensor.html#outputRanges-prop',0,'QSensor']]],
  ['overwritemode',['overwriteMode',['https://doc.qt.io/qt-5/qplaintextedit.html#overwriteMode-prop',0,'QPlainTextEdit::overwriteMode()'],['https://doc.qt.io/qt-5/qtextedit.html#overwriteMode-prop',0,'QTextEdit::overwriteMode()']]]
];
