var searchData=
[
  ['background',['background',['http://doc.qt.io/qt-5/qmdiarea.html#background-prop',0,'QMdiArea']]],
  ['backgroundbrush',['backgroundBrush',['http://doc.qt.io/qt-5/qgraphicsscene.html#backgroundBrush-prop',0,'QGraphicsScene::backgroundBrush()'],['http://doc.qt.io/qt-5/qgraphicsview.html#backgroundBrush-prop',0,'QGraphicsView::backgroundBrush()']]],
  ['backgroundcolor',['backgroundColor',['http://doc.qt.io/qt-5/qwebenginepage.html#backgroundColor-prop',0,'QWebEnginePage']]],
  ['backgroundvisible',['backgroundVisible',['http://doc.qt.io/qt-5/qplaintextedit.html#backgroundVisible-prop',0,'QPlainTextEdit']]],
  ['baselineoffset',['baselineOffset',['http://doc.qt.io/qt-5/qquickitem.html#baselineOffset-prop',0,'QQuickItem']]],
  ['basesize',['baseSize',['http://doc.qt.io/qt-5/qwidget.html#baseSize-prop',0,'QWidget']]],
  ['baseurl',['baseUrl',['http://doc.qt.io/qt-5/qtextdocument.html#baseUrl-prop',0,'QTextDocument']]],
  ['batchsize',['batchSize',['http://doc.qt.io/qt-5/qlistview.html#batchSize-prop',0,'QListView']]],
  ['blockcount',['blockCount',['http://doc.qt.io/qt-5/qtextdocument.html#blockCount-prop',0,'QTextDocument::blockCount()'],['http://doc.qt.io/qt-5/qplaintextedit.html#blockCount-prop',0,'QPlainTextEdit::blockCount()']]],
  ['blockupdates',['blockUpdates',['http://doc.qt.io/qt-5/qwebchannel.html#blockUpdates-prop',0,'QWebChannel']]],
  ['blurhints',['blurHints',['http://doc.qt.io/qt-5/qgraphicsblureffect.html#blurHints-prop',0,'QGraphicsBlurEffect']]],
  ['blurradius',['blurRadius',['http://doc.qt.io/qt-5/qgraphicsblureffect.html#blurRadius-prop',0,'QGraphicsBlurEffect::blurRadius()'],['http://doc.qt.io/qt-5/qgraphicsdropshadoweffect.html#blurRadius-prop',0,'QGraphicsDropShadowEffect::blurRadius()']]],
  ['bottom',['bottom',['http://doc.qt.io/qt-5/qintvalidator.html#bottom-prop',0,'QIntValidator::bottom()'],['http://doc.qt.io/qt-5/qdoublevalidator.html#bottom-prop',0,'QDoubleValidator::bottom()']]],
  ['bottomleft',['bottomLeft',['http://doc.qt.io/qt-5/qgeorectangle.html#bottomLeft-prop',0,'QGeoRectangle']]],
  ['bottomright',['bottomRight',['http://doc.qt.io/qt-5/qgeorectangle.html#bottomRight-prop',0,'QGeoRectangle']]],
  ['bsptreedepth',['bspTreeDepth',['http://doc.qt.io/qt-5/qgraphicsscene.html#bspTreeDepth-prop',0,'QGraphicsScene']]],
  ['buffersize',['bufferSize',['http://doc.qt.io/qt-5/qsensor.html#bufferSize-prop',0,'QSensor']]],
  ['busy',['busy',['http://doc.qt.io/qt-5/qsensor.html#busy-prop',0,'QSensor']]],
  ['button',['button',['http://doc.qt.io/qt-5/qmouseeventtransition.html#button-prop',0,'QMouseEventTransition']]],
  ['buttonsymbols',['buttonSymbols',['http://doc.qt.io/qt-5/qabstractspinbox.html#buttonSymbols-prop',0,'QAbstractSpinBox']]]
];
