var searchData=
[
  ['rangeaccessflags',['RangeAccessFlags',['https://doc.qt.io/qt-5/qopenglbuffer.html#RangeAccessFlag-enum',0,'QOpenGLBuffer']]],
  ['rawheader',['RawHeader',['https://doc.qt.io/qt-5/qnetworkcachemetadata.html#RawHeader-typedef',0,'QNetworkCacheMetaData']]],
  ['rawheaderlist',['RawHeaderList',['https://doc.qt.io/qt-5/qnetworkcachemetadata.html#RawHeaderList-typedef',0,'QNetworkCacheMetaData']]],
  ['rawheaderpair',['RawHeaderPair',['https://doc.qt.io/qt-5/qnetworkreply.html#RawHeaderPair-typedef',0,'QNetworkReply']]],
  ['readfunc',['ReadFunc',['https://doc.qt.io/qt-5/qsettings.html#ReadFunc-typedef',0,'QSettings']]],
  ['reduceoptions',['ReduceOptions',['https://doc.qt.io/qt-5/qtconcurrent.html#ReduceOption-enum',0,'QtConcurrent']]],
  ['reference',['reference',['https://doc.qt.io/qt-5/qjsonarray.html#reference-typedef',0,'QJsonArray::reference()'],['https://doc.qt.io/qt-5/qfuture-const-iterator.html#reference-typedef',0,'QFuture::const_iterator::reference()'],['https://doc.qt.io/qt-5/qlinkedlist.html#reference-typedef',0,'QLinkedList::reference()'],['https://doc.qt.io/qt-5/qlist.html#reference-typedef',0,'QList::reference()'],['https://doc.qt.io/qt-5/qset.html#reference-typedef',0,'QSet::reference()'],['https://doc.qt.io/qt-5/qstring.html#reference-typedef',0,'QString::reference()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#reference-typedef',0,'QVarLengthArray::reference()'],['https://doc.qt.io/qt-5/qvector.html#reference-typedef',0,'QVector::reference()']]],
  ['relation',['Relation',['https://doc.qt.io/qt-5/qaccessible.html#RelationFlag-enum',0,'QAccessible']]],
  ['remoteconnecting',['RemoteConnecting',['https://doc.qt.io/qt-5/class_qt_data_sync_1_1_remote_connector.html#a3559486872598c62e9cf7dafe0d393a2a161f11314bd5eca8dd6e39063713f905',0,'QtDataSync::RemoteConnector']]],
  ['remotedisconnected',['RemoteDisconnected',['https://doc.qt.io/qt-5/class_qt_data_sync_1_1_remote_connector.html#a3559486872598c62e9cf7dafe0d393a2a6a47d3f967ad7f68931cfc56e5534bba',0,'QtDataSync::RemoteConnector']]],
  ['remoteloadingstate',['RemoteLoadingState',['https://doc.qt.io/qt-5/class_qt_data_sync_1_1_remote_connector.html#a3559486872598c62e9cf7dafe0d393a2a3bba428a35ca83baab47f459b66e32dd',0,'QtDataSync::RemoteConnector']]],
  ['remoteready',['RemoteReady',['https://doc.qt.io/qt-5/class_qt_data_sync_1_1_remote_connector.html#a3559486872598c62e9cf7dafe0d393a2a59b54f89d10b278f7cb8717112f090ec',0,'QtDataSync::RemoteConnector']]],
  ['renderflags',['RenderFlags',['https://doc.qt.io/qt-5/qwidget.html#RenderFlag-enum',0,'QWidget::RenderFlags()'],['https://doc.qt.io/qt-5/qtextitem.html#RenderFlag-enum',0,'QTextItem::RenderFlags()']]],
  ['renderhints',['RenderHints',['https://doc.qt.io/qt-5/qpainter.html#RenderHint-enum',0,'QPainter']]],
  ['renderingflags',['RenderingFlags',['https://doc.qt.io/qt-5/qsgrendernode.html#RenderingFlag-enum',0,'QSGRenderNode']]],
  ['result',['Result',['https://doc.qt.io/qt-5/qgesturerecognizer.html#ResultFlag-enum',0,'QGestureRecognizer']]],
  ['reverse_5fiterator',['reverse_iterator',['https://doc.qt.io/qt-5/qbytearray.html#reverse_iterator-typedef',0,'QByteArray::reverse_iterator()'],['https://doc.qt.io/qt-5/qlinkedlist.html#reverse_iterator-typedef',0,'QLinkedList::reverse_iterator()'],['https://doc.qt.io/qt-5/qlist.html#reverse_iterator-typedef',0,'QList::reverse_iterator()'],['https://doc.qt.io/qt-5/qset.html#reverse_iterator-typedef',0,'QSet::reverse_iterator()'],['https://doc.qt.io/qt-5/qstring.html#reverse_iterator-typedef',0,'QString::reverse_iterator()'],['https://doc.qt.io/qt-5/qvarlengtharray.html#reverse_iterator-typedef',0,'QVarLengthArray::reverse_iterator()'],['https://doc.qt.io/qt-5/qvector.html#reverse_iterator-typedef',0,'QVector::reverse_iterator()']]],
  ['routeoptimizations',['RouteOptimizations',['https://doc.qt.io/qt-5/qgeorouterequest.html#RouteOptimization-enum',0,'QGeoRouteRequest']]],
  ['routingfeatures',['RoutingFeatures',['https://doc.qt.io/qt-5/qgeoserviceprovider.html#RoutingFeature-enum',0,'QGeoServiceProvider']]]
];
