#ifndef QTAUTOUPDATERCORE_GLOBAL_H
#define QTAUTOUPDATERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT_BUILD_AUTOUPDATERCORE_LIB)
#	define Q_AUTOUPDATERCORE_EXPORT Q_DECL_EXPORT
#else
#	define Q_AUTOUPDATERCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // QTAUTOUPDATERCORE_GLOBAL_H
