#ifndef QTAUTOUPDATERWIDGETS_GLOBAL_H
#define QTAUTOUPDATERWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef QT_STATIC
#  if defined(QT_BUILD_AUTOUPDATERWIDGETS_LIB)
#    define Q_AUTOUPDATERWIDGETS_EXPORT Q_DECL_EXPORT
#  else
#    define Q_AUTOUPDATERWIDGETS_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_AUTOUPDATERWIDGETS_EXPORT
#endif

#endif // QTAUTOUPDATERWIDGETS_GLOBAL_H
