#ifndef QTAUTOUPDATER_GLOBAL_H
#define QTAUTOUPDATER_GLOBAL_H

#include <QtGlobal>

#if defined(QTAUTOUPDATER_LIBRARY)
#  define QTAUTOUPDATERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTAUTOUPDATERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTAUTOUPDATER_GLOBAL_H
